enum BackEndStatusCode {
  UNKNOWN_ERROR = 99,
  AUTHENTICATION_EMAIL_NOT_FOUND = 1001,
  AUTHENTICATION_EMAIL_ALREADY_IN_USE = 1002,
  AUTHENTICATION_ACCOUNT_NOT_VERIFIED = 1003,
  AUTHENTICATION_ACCOUNT_DISABLED = 1004,
  AUTHENTICATION_PASSWORD_INCORRECT = 1005,
  AUTHENTICATION_PASSWORD_NOT_MATCHES = 1006,
  AUTHENTICATION_VERIFICATION_CODE_EXPIRED = 1007,
  AUTHENTICATION_VERIFICATION_CODE_INCORRECT = 1008,
  AUTHENTICATION_RESEND_VERIFICATION_CODE = 1009,
  AUTHENTICATION_RESET_PASSWORD_LINK_EXPIRED = 1010,
  AUTHENTICATION_NEED_CHANGE_PASSWORD = 1011
}

export default BackEndStatusCode;
